### ISSUE TITLE
Implement videos and audio

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-web#28]
Right now, videos are marked as not supported on this version of the app. To be honest, they have never worked well on the original Pulse web app either. So, I will see what I can do about them for this version. The decryption is a huge amount of processing power against a large base64 encoded string, and takes too long.

### To fix

We need a way to download and decrypt the videos (or other large media), in the background. [Web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) are the way to go, but there is some overhead for getting them into our current setup.

With webpack, we would have to use [this](https://github.com/webpack-contrib/worker-loader). However, it requires at least Node v6.9.0 and Webpack v4.0.0. We are currently on 2.x of Webpack and need to update. I also found [this issue](https://github.com/vuejs/vue-cli/issues/2276) for Vuejs support

Once the web workers are up and running, from the media loader:

* the background worker will download, decrypt, and store the decrypted media in the index db, just like everything currently works.
* when that is complete, we will have to post a message to the UI to re-update the view and load that image from the index db

If this works, we can probably use it on all of the different images/media types, not just videos and audio. It would at least make the page smooth scrolling during the decryption process. Right now, everything hangs up.

https://developer.mozilla.org/en-US/docs/Tools/Performance/Scenarios/Intensive_JavaScript#Using_web_workers

**Comment by PhilBax** [comment]
Even if embedded videos don't work, it would be nice to have the link to download the video for play offline like we used to have. That worked just fine for me previously, but currently I have literally no 
option in Pulse to view videos my wife sends me. :/

**Comment by PhilBax** [comment]
Just ran into this with the audio as well. Restoring the download link would be really nice. :(
