### ISSUE TITLE
New Web App Settings

### ISSUE THREAD

**Issue by thesamim** [klinker-apps/messenger-web#38]
https://pulsesms.app/settings

This is on Firefox 62.07b

Don't see a save button. 
Settings are not auto saved
Selecting a different them does not change current selected theme

figures: upgraded to 62.08b and everything is working now. Don't know if it's the version or the FF restart that fixed it.

I think this issue can just be closed. Sorry.

**Comment by klinker24** [comment]
There is a save button right on the dialog for entering the colors. Everything else is auto saves
![screenshot_20180713-135151](https://user-images.githubusercontent.com/4874287/42708867-295d7648-86a4-11e8-9438-cadb3ecaf125.png)

Maybe I don't understand what you are talking about. Feel free to comment back with more details, or a picture of what you are seeing, and I can re-open
