### ISSUE TITLE
contacts with emojis in name bug out

### ISSUE THREAD

**Issue by qwe282** [klinker-apps/messenger-web#43]
https://imgur.com/1djA6sK

**Comment by klinker24** [comment]
This has already been fixed. Try it on the web, then use the ctrl + R key combination to pull the latest changes into the desktop app.

https://github.com/klinker-apps/messenger-web/commit/29195223f618fe45c97cf8f31fe9fbe6e289dfdc

**Comment by qwe282** [comment]
nope jkust checked was broken with the 3.0 update the old one is fixed but pulsesms.app or new interface broke it

**Comment by klinker24** [comment]
It has already been fixed, if you read and follow the instructions I have provided. I know it was broken. It doesn't require a new version of the desktop app to fix it. Please follow my instructions.

![screen shot 2018-07-23 at 10 18 33 am](https://user-images.githubusercontent.com/4874287/43085947-d4ace7da-8e61-11e8-801e-2d03653d3046.png)

**Comment by qwe282** [comment]
ok can olny replicate with heart emoji

**Comment by qwe282** [comment]
you are right its fixed for everything but for some odd resone appears on this specific emoji

**Comment by Serubin** [comment]
<img width="275" alt="screen shot 2018-07-23 at 11 32 47 am" src="https://user-images.githubusercontent.com/1234465/43086771-28095936-8e6c-11e8-84dc-639fa7bd70a8.png">
Heart emoji works just fine.

**Comment by qwe282** [comment]
thats unicode heart red heart ❤️      not this ♥

**Comment by Serubin** [comment]
Pulse is designed to use your system default. I'm going to lock this thread as this is solve and the system is working as intended.
