### ISSUE TITLE
Bad display of emojis in contact names

### ISSUE THREAD

**Issue by wilomgfx** [klinker-apps/messenger-web#44]
![](https://dzwonsemrish7.cloudfront.net/items/1a0P0c1d302W0U0j0v38/Image%202018-07-26%20at%201.31.36%20PM.png?v=76574e22)

Its supposed to be 
![](https://dzwonsemrish7.cloudfront.net/items/1l1g3R1G153t0m3Z3M30/Image%202018-07-26%20at%201.34.52%20PM.png?v=1b082a4a)

**Comment by klinker24** [comment]
https://github.com/klinker-apps/messenger-web/commit/dae3c5dc391c23a6249c099610769e5868dfcf80
