### ISSUE TITLE
[Feature Request] NextCloud integration?  🌩

### ISSUE THREAD

**Issue by thedonquixotic** [klinker-apps/messenger-web#48]
This might be outside the scope of what you folks intend to do with this application but I'd love to point ya'll in the direction of the NextCloud personal cloud project. They already have some SMS integration built as an optional native cloudapp, but I think it would be really cool if someone who was hosting their own NextCloud server could access Pulse from within their NextCloud cloud. It would be a great way to add onto the features of Pulse, backing-up and syncing messages, photos, and contacts, etc. 

Anyway just an idea. Love the work! You guys are awesome! This is by far my favorite SMS app for android and desktop! 😍

**Comment by klinker24** [comment]
That probably isn't something that I would be interested in for pulse, sorry. A big focus of my app is the simplicity and the integration that it provides, all in one. There isn't really any configuration, you just create an account on the phone and it does everything for you automatically.

If your concern around this is privacy, everything in Pulse is end to end encrypted, so it isn't like that should be a real concern

**Comment by thedonquixotic** [comment]
No worries, just wanted to drop the idea by. Thanks for all your work!
