### ISSUE TITLE
webpage reloads to button of messages instead of top

### ISSUE THREAD

**Issue by bcurran3** [klinker-apps/messenger-web#68]
About 4-5 days ago I noticed a change in the behavior of https://pulsesms.app.

Now after clicking a message thread and viewing, when I click Conversations the page scrolls to the bottom of the screen displaying the oldest messages instead of returning to the top with the newest messages.

Google Chrome is up to date
Version 72.0.3626.96 (Official Build) (64-bit)

I have not had time to check with other browsers.

**Comment by klinker24** [comment]
I am not able to reproduce this, so I will need more of a description or steps that I can go through, to reproduce it.

**Comment by bcurran3** [comment]
Thanks for the fast response.

So I'm thinking to myself how to provide more data for this...

I opened an incognito window and tried to replicate, and it worked fine.

Maybe something in my cache? I'll wipe and see.

Just cleared cookies and cache and the same thing happens.

Running with the idea it must be a "just me" thing and closing.

**Comment by bcurran3** [comment]
UPDATE: It just resolved itself. Maybe I didn't wait long enough for the cache to get completely wiped? Dunno, just happy again. :)
