### ISSUE TITLE
Scheduled Messages: Repeat Every nth Period

### ISSUE THREAD

**Issue by mcjathan** [klinker-apps/messenger-web#69]
**Feature Request**
I request an enhancement to Pulse's recurring scheduled messages.  Please add an "nth" modifier to scheduled messages.  Currently, Pulse assumes n = 1.  Please enhance so that n can be user specified: Repeat every nth day, Repeat every nth week, etc.  For example:

* Repeat every 1 day
* Repeat every 2 days
* Repeat every 3 weeks
* Repeat every 6 months

**Comment by klinker24** [comment]
I will reopen this in the roadmap repo, since it doesn't really have anything to do with the web app.
