### ISSUE TITLE
It's very slow and delays sending msg on web app and chrome extension, Since upgrade Android to 7.1.2

### ISSUE THREAD

**Issue by cougar999** [klinker-apps/messenger-web#70]
Last night my phone updated to Android 7.1.2

Then, when I am sending text on web app or chrome extension, the sending speed is very slow, and I can't get the message on android app even it says the message is sent successful on the web App.

The Android app is working well.

**Comment by Serubin** [comment]
In the app under my account try the "Refresh Account" option. That may help.

**Comment by cougar999** [comment]
Tried, the same issue exists. Can't use web app and Chrome app now.

**Comment by cougar999** [comment]
This issue still exists, it must be wrong by something in the windows or Web App, the Android App is working well.

I have to consider a swap to another App if it's still not working.

**Comment by Serubin** [comment]
@klinker24

**Comment by klinker24** [comment]
Pulse relies on Google Play Services to send messages from the web, to the device, as a push notification. If this just started happening after an upgrade to Android, it sounds to me that something on the system side has been messed up.

Restarting the phone will restart the Google Play Services connection, as well as deleting and recreating the account (which is what refreshing the account does). If neither of those solve the issue, then something is wrong with the Google Play Services configuration on your device.

**Comment by cougar999** [comment]
The Google play service is running. I fix the play service by installing some Apps, it works, but still very very slow...

**Comment by klinker24** [comment]
I am not going to be able to control the transmission time, sorry. Delivery is on Google

With every message that you send from another device, I send two push notifications.

* The first has a zero TTL signature, which tells firebase that it should be delivered now or never. If it doesn't make it to your device within 10 seconds, then it is discarded. There is no configuration that can make the push notifications get delivered faster than this.
* The second is a long life message, telling firebase to deliver it as soon as possible. This message lives for weeks, until Google is able to deliver it.

The app discarded whatever push notification comes in second.

**Comment by cougar999** [comment]
I'll try to degrade Android to see whether I can avoid this issue.

**Comment by cougar999** [comment]
I found an interesting thing, maybe can help to debug the issue.
If I sent something from the web app or windows app for a long time ago, if I didn't receive the message from Android App, as long as I click the button which it is at the right top(as the picture shows), for a couple of times, then I can get the message from the Android App, seems it refreshed the message queue through server and all the apps....

Is that the reason like you said? Google play service delay?



![pulse-20190329102115](https://user-images.githubusercontent.com/1323406/55269339-32d0a100-52e6-11e9-9b32-26d2ca4ab42d.jpg)

**Comment by klinker24** [comment]
That action makes a data call, opening your phone to receive the push notification.
