### ISSUE TITLE
Can't attatch images via Web or Pulse SMS App

### ISSUE THREAD

**Issue by YogiOz** [klinker-apps/messenger-web#71]
Can't attatch images via Web or Pulse SMS App...

When I attach (or try to) an image in the Web interface or Pulse App it does not send.  When I attatch an image it continously tries to attach but fails.

**Comment by Serubin** [comment]
Does this happen in the android app as well? 

I just tested out on my phone and the web app and was unable to reproduce. Would you be able to produce the steps you took and perhaps a video of the issue?

**Comment by YogiOz** [comment]
Not that I know of - just web and Pulse App

**Comment by Serubin** [comment]
To clarify, what do you mean by Pulse App? I presume you mean the Pulse App on your phone? This is what I mean by the android app.

**Comment by YogiOz** [comment]
Steps:

Open SMS App
Select recipient
attach image
![Capture](https://user-images.githubusercontent.com/43358407/54574077-09d92200-4a43-11e9-9436-56f6891b3a50.PNG)

**Comment by Serubin** [comment]
What takes place on your phone?

**Comment by YogiOz** [comment]
Pulse App is this: https://blog.klinkerapps.com/pulse-sms-desktop-apps/

**Comment by Serubin** [comment]
Go it, and on your phone?

**Comment by YogiOz** [comment]
Phone works OK...this is via Desktop App or Website

**Comment by Serubin** [comment]
Please provide any logs you are able to from the developer console

**Comment by YogiOz** [comment]
There are no logs that I know of from using a windows desktop app...

**Comment by klinker24** [comment]
"View" -> "Toggle Developer Tools" brings up the same developer console that you would see in Chrome.

**Comment by YogiOz** [comment]
I can't access my phone at this stage - only desktop app/website.

**Comment by klinker24** [comment]
I am not talking about the phone, nor did I reference the phone anywhere in my reply. We are discussing the web and desktop apps and how to access the developer console to pull the logs.

**Comment by YogiOz** [comment]
pulsesms.app/:1 Access to XMLHttpRequest at 'https://firebasestorage.googleapis.com/v0/b/messenger-42616.appspot.com/o?name=b7fe35984afbd5045c8f66fd7020ca234852f488d012bacb5a7f4789524d314f%2F727152172896649' from origin 'https://pulsesms.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
index.js:123 WebSocket connection to 'wss://api.messenger.klinkerapps.com/api/v1/stream?account_id=b7fe35984afbd5045c8f66fd7020ca234852f488d012bacb5a7f4789524d314f' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by Serubin** [comment]
Just to add this again @klinker24, I couldn't reproduce this error on any of my clients.

**Comment by klinker24** [comment]
@YogiOz It seems to me that whatever network, device, or browser you are on, is blocking the image upload. Sorry that is not something that we will be able to affect on our side

```
pulsesms.app/:1 Access to XMLHttpRequest at 'https://firebasestorage.googleapis.com/v0/b/messenger-42616.appspot.com/o?name=b7fe35984afbd5045c8f66fd7020ca234852f488d012bacb5a7f4789524d314f%2F727152172896649' from origin 'https://pulsesms.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

This message is indicating that it cannot access the Firebase Storage APIs.

**Comment by YogiOz** [comment]
This has started working again...
