### ISSUE TITLE
Emojis are not inserted at the cursor position

### ISSUE THREAD

**Issue by simonbcn** [klinker-apps/messenger-web#72]
```
Arch Linux
GNOME Shell 3.32.0
https://pulsesms.app/compose
```
If I write a message and then want to add an emoji in the middle of the message, _pulsesms_ inserts it at the end of the message, not at the cursor position.

**Comment by simonbcn** [comment]
It still fails.

**Comment by klinker24** [comment]
I haven't deployed anything yet.
