### ISSUE TITLE
Pulsesms.app intermittently displays no messages

### ISSUE THREAD

**Issue by Brebinator** [klinker-apps/messenger-web#74]
CASE:  App on Windows 10E 64-bit

When reading a message from a sender, there may be another sender message in a row item in the list on the left that is in BOLD detailing unread.

Directly clicking the BOLD Row of the unread message displayed the sender details in the top but no content.

WORKAROUND: To click on all conversations to push the list into the main view and then to select the message from there makes it viewable. This is intermittent but frequent throughout a day.

**Comment by klinker24** [comment]
Sorry, I am not able to replicate this issue by just having an unread item in the conversation list, then clicking it. Are there any other steps that you can provide?

**Comment by klinker24** [comment]
Sorry, but without more information, I have to close this issue. 

Please feel free to report back, if you are able to provide consistent steps to reproduce this issue or have more information that you think will be helpful to solving it.

**Comment by Brebinator** [comment]
Sorry mate I just read this and i have been rebuilding computers after a flood. I just didn't get time to look at it.
________________________________
