### ISSUE TITLE
Timstamps seem not to be on all messages

### ISSUE THREAD

**Issue by Brebinator** [klinker-apps/messenger-web#75]
![Screenshot_2019-03-26-18-36-51-894_xyz klinker messenger](https://user-images.githubusercontent.com/8649777/54982382-71204480-4ff6-11e9-95be-bc01d79e2b7e.png)

In both the webapp and also the phone  app there seems to be an inconsistency in the display of timestamps. the stamp appears for the majority of messages but a good portion are displayed without it.

**Comment by klinker24** [comment]
If you search "timestamp" on the help page, I go in to detail on when it is shown

https://messenger.klinkerapps.com/help
