### ISSUE TITLE
Toggle Mass text versus MMS

### ISSUE THREAD

**Issue by ems170** [klinker-apps/messenger-web#76]
Please consider adding a way to toggle between mass text and MMS on the windows and web app. There are many applications to this to justify the need. There are many times where a question will need to be sent to multiple people and there is not a desire to create an out of control group chat. Then there are other times where a group chat is what is desired. A real-life example is when I am trying to fill an open shift at work. I may send it out to 20 people. I don't want and nor do they to see the 20 replies back about availability. This is an application of using the mass text option. I love your platform and it does everything well with this exception. Thank you for your consideration and time.

**Comment by ems170** [comment]
<img width="405" alt="Capture" src="https://user-images.githubusercontent.com/44934264/57571386-8f41d880-73db-11e9-941d-02e391238719.PNG">

Here is an example of how the Verizon windows app handles the switch

**Comment by klinker24** [comment]
We will just combine this request, with this one.

https://github.com/klinker-apps/messenger-issues/issues/685#issuecomment-491519603

**Comment by ems170** [comment]
Sounds good, I didn't know if I should report them separately as a per platform request. Whatever works for you. Thank you for your consideration.
