### ISSUE TITLE
Draft Feature Missing

### ISSUE THREAD

**Issue by the-sides** [klinker-apps/messenger-web#77]
The Pulse Android app's draft feature works perfectly for messages I'm still working on, yet I've noticed the web app lacks the proper support. 
If you wouldn't mind, I'd love to look into the codebase to find an implementation, at least for my sake.

**Comment by klinker24** [comment]
Feel free to implement this, if you have the time. This feature request is tracked, here https://github.com/klinker-apps/messenger-issues/issues/806
