### ISSUE TITLE
Unable to scroll down and view all conversations on Pulse Web. 

### ISSUE THREAD

**Issue by rrtigga** [klinker-apps/messenger-web#78]
Unable to scroll down to view all conversations on the web app. It has a fixed amount and doesn't pull in all the messages I have on mobile. 

![pulse-image](https://user-images.githubusercontent.com/6754090/59217473-de159600-8b72-11e9-8b42-82e1d2c24cb5.jpg)
<img width="1440" alt="Screen Shot 2019-06-10 at 11 25 55 AM" src="https://user-images.githubusercontent.com/6754090/59217480-e241b380-8b72-11e9-9950-f9956a27f9ff.png">
<img width="492" alt="Screen Shot 2019-06-10 at 11 25 47 AM" src="https://user-images.githubusercontent.com/6754090/59217493-e53ca400-8b72-11e9-8a18-655aed01923d.png">

**Comment by klinker24** [comment]
The web and desktop applications only display the latest 75 conversations, for performance reasons. This is not something that I am open to changing. 

If you want to see more than that, you can archive the older conversations, or even place them in folders. There is no limit to the number of archived conversations that are loaded into the web and desktop applications. The only limit is on the main conversation list.
