### ISSUE TITLE
Why your pulsesms.app design is so unproductive?

### ISSUE THREAD

**Issue by midenok** [klinker-apps/messenger-web#80]
It is only 7 conversations that was fit on my 1600 x 900 monitor.

**Comment by klinker24** [comment]
`command + -` will zoom out of the webpage. You can use this on any website, with any modern browser.. You can change the font and size of the app to your hearts content this way. It will allow you to fit as many conversations as you want, on the screen.

I am sorry that you think the design is pathetic. Please enjoy the rest of your day.

**Comment by midenok** [comment]
No, it is not a good solution as it also zooms out horizontally and does not use horizontal space.

**Comment by klinker24** [comment]
Sorry. The web app is open source and easy to host. Feel free to customize the UI however you choose. I enjoy the UI of the app and do not feel the need to squish as many conversations as I can, into the page. That is not modern design, but you have already said that you do not have a taste for modern design, which is a personal preference.
