### ISSUE TITLE
How to change password?

### ISSUE THREAD

**Issue by midenok** [klinker-apps/messenger-web#81]
There is no clear understanding from that page:

https://messenger.klinkerapps.com/forgot_password.html

Should I delete my account? If I do so will I lose my lifetime subscription? Please, clarify this on that page.

**Comment by klinker24** [comment]
That page provides two explicit options. If you are signed in on the phone, refresh the account. Otherwise, delete and recreate it. That page is also explicit that any purchases you made will be restored.

> Purchases are stored on your Google account and will be automatically restored to the new account that you create. All the messages you see in the phone app will be uploaded to the new account.
