### ISSUE TITLE
Update Vue

### ISSUE THREAD

**Issue by Serubin** [klinker-apps/messenger-web#82]
Update Vuejs to latest version. Newer versions of Vue provide an improved build system and better upgrading and integration of tools. 

This provides a nice launching point to cleaning up the code base.

Current progress:
* [x] Initial conversion/update (89302af6309c2e55136cfcdbf2cf595f919ad011)
* [x] Fix service worker (5a02927d33926833b491830ac677fec6eed17a55)
* [x] Fix favicon (it was still green on initial testing)? (84ab8b86d0637cdf510112dc15cfcc5dda0fecca)
* [x] Verify deployment works

See `feature/update-vue` branch.

**Comment by Serubin** [comment]
Service-worker loader is not currently doing everything it's supposed too. 

Error on start:
```
uncaught exception: Object
The Notification permission may only be requested from inside a short running user-generated event handler. login
Failed to register/update a ServiceWorker for scope ‘https://pulse.serubin.net/’: Load failed with status 404 for script ‘https://pulse.serubin.net/service-worker.js’.
TypeError: ServiceWorker script at https://pulse.serubin.net/service-worker.js for scope https://pulse.serubin.net/ encountered an error during installation.
```

**Comment by Serubin** [comment]
Service workers are functional and favicons/icons are perfect.

**Comment by Serubin** [comment]
Working well at pulse-beta.serubin.net

**Comment by klinker24** [comment]
Done and deployed 👍
